### ISSUE TITLE
A question in this Problem

### ISSUE THREAD

**Issue by messi-yang** [acearth/LeetCodePractice#7]
In [https://github.com/acearth/LeetCodePractice/blob/master/divide_Without_divide.rb](url)

`res=go_divide(~divident+1, ~divisor+1) if divident<0 && divisor < 0`

I'm intersted in why you use ~divident+1 rather than just -divident

Because the sign **-** equals to divisror or multiplied ?

Thank you !

**Comment by acearth** [comment]
Yes, this problem requires solution without division or multiply. Due to -dividend equals to -1 \* dividend, so I used bit operation instead.

note: 'divident'is a typo. and there should have one space between operand and operator. Could you improve it  ? ( change and test and pull request)

**Comment by messi-yang** [comment]
Thank you for response of answer.
I will think about it after my work today .
